---
name: Deploy PR Preview
description: Deploy PR Preview
inputs:
  folder:
    description: Folder to deploy
    required: true
  branch:
    description: Branch to deploy
    required: false
    default: gh-pages
  umbrella-dir:
    description: Directory containing all previews
    required: false
    default: pr-preview

runs:
  using: composite
  steps:
    - name: Deploy PR Preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ${{ inputs.folder }}
        preview-branch: ${{ inputs.branch }}
        umbrella-dir: ${{ inputs.umbrella-dir }}
