name: Action Test

on:
  push:
    branches: [main, master]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
  deploy-and-preview:
    name: Action Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages and Deploy PR Preview using this action
        uses: chvmvd/github-pages-deploy-and-preview-action@v1.0.0
        with:
          folder: test
