name: Prettier

on:
  pull_request:

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash

      - name: Run Prettier
        run: npm run format
        shell: bash
